In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.svm import OneClassSVM
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.tree import plot_tree

In [2]:
df = pd.read_csv('Data/selected_features.csv')

In [3]:
df.head()

,NACCID,CDRSUM,DECIN,MOSLOW,MEMORY,SPEECH,BILLS,TRAVEL,MOFALLS,MOTREM,...,TOBAC30,TOBAC100,SMOKYRS,PACKSPER,QUITSMOK,ALCOHOL,DIABETES,HYPERTEN,CVHATT,SEX
0,NACC235922,3.5,1,0,1.0,-4,1,0,0,0,...,0,1,22,2,40,0,0,1,0,2
1,NACC383757,0.5,8,0,0.5,-4,0,0,0,0,...,0,1,15,5,28,2,0,1,0,1
2,NACC418253,2.0,1,0,1.0,-4,0,0,0,0,...,0,1,10,2,30,0,0,0,0,2
3,NACC433163,0.5,1,0,0.5,-4,8,0,0,1,...,0,1,2,2,17,0,0,0,0,1
4,NACC476187,5.0,1,0,1.0,-4,3,3,0,0,...,0,1,25,2,45,0,0,1,0,1

In [4]:
df = df.drop('NACCID', axis=1)

**Linear Regression**

In [5]:
#dummy coding categorical variables
df_encoded = pd.get_dummies(df, columns=['SEX', 'TOBAC30', 'TOBAC100', 'ALCOHOL', 'DIABETES', 'HYPERTEN', 'CVHATT', 'DECIN', 'MOSLOW', 'MEMORY', 'SPEECH', 'BILLS', 'TRAVEL', 'MOFALLS', 'MOTREM'], drop_first=True)
y = df_encoded['CDRSUM']
X = df_encoded.drop(columns=['CDRSUM'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [11]:
y

0        3.5
1        0.5
2        2.0
3        0.5
4        5.0
        ...
13684    0.0
13685    0.0
13686    0.0
13687    0.0
13688    0.0
Name: CDRSUM, Length: 13689, dtype: float64

In [6]:
df_encoded

,CDRSUM,NACCAGE,NACCBMI,SMOKYRS,PACKSPER,QUITSMOK,SEX_2,TOBAC30_1,TOBAC30_9,TOBAC100_1,...,TRAVEL_0,TRAVEL_1,TRAVEL_2,TRAVEL_3,TRAVEL_8,TRAVEL_9,MOFALLS_1,MOFALLS_9,MOTREM_1,MOTREM_9
0,3.5,72,31.9,22,2,40,1,0,0,1,...,1,0,0,0,0,0,0,0,0,0
1,0.5,76,27.2,15,5,28,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
2,2.0,73,20.8,10,2,30,1,0,0,1,...,1,0,0,0,0,0,0,0,0,0
3,0.5,77,26.8,2,2,17,0,0,0,1,...,1,0,0,0,0,0,0,0,1,0
4,5.0,84,26.7,25,2,45,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13684,0.0,69,27.3,7,1,25,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
13685,0.0,70,26.9,7,1,25,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
13686,0.0,71,26.7,7,1,25,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
13687,0.0,72,26.8,7,1,25,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
13688,0.0,73,27.2,7,1,25,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0

In [22]:

# Create a LinearRegression object
model = LinearRegression()

# Fit the model to the training data
model.fit(X_train, y_train)

# Once the model is trained, you can make predictions on the test data
predictions = model.predict(X_test)

In [23]:
print('model intercept :', model.intercept_) 
print('model coefficients : ', model.coef_) 
# Calculate Mean Squared Error (MSE)
mse = mean_squared_error(y_test, predictions)
print("Mean Squared Error (MSE):", mse)

# Calculate R-squared
r2 = r2_score(y_test, predictions)
print("R-squared:", r2)

# Calculate Mean Absolute Error (MAE)
mae = mean_absolute_error(y_test, predictions)
print("Mean Absolute Error (MAE):", mae)

model intercept : -0.6478909571391449
model coefficients :  [-4.92143018e-03  2.30510592e-03  3.36029315e-03  6.38953729e-03
 -1.85078725e-03 -6.73891172e-02 -1.52729421e-02  2.42826573e-02
  1.06026135e+00  1.23399245e+00  1.15816289e-01  9.00604315e-02
 -6.68366980e-01  1.43187531e-02  1.19899009e-01 -1.85863447e-01
 -8.99719864e-03 -2.91861827e-03  2.82636735e-01 -2.49965792e-01
 -6.44238763e-03 -3.65654584e-01  1.38055139e-01 -1.53682661e-02
  6.69278757e-03  3.27659648e-01 -1.22924783e-01  7.62181583e-01
  2.78859383e+00  6.68046904e+00  1.19121448e+01  4.43175975e-02
  8.49283917e-02  6.50359197e-01  1.62483121e+00  2.99179363e+00
  1.79084529e+00 -3.00287251e-02  5.59773103e-02  3.85432470e-01
  1.11253406e+00  4.49824516e-01 -4.41892092e-02 -1.12589757e-01
  1.26846058e-01  5.44820099e-01  1.60634405e+00  2.33514134e-01
 -4.69384166e-01  5.79410179e-01  5.29548656e-01 -1.53173162e-01
 -4.11361988e-01]
Mean Squared Error (MSE): 0.7459778745788452
R-squared: 0.9130803861566442
Mean Absolute Error (MAE): 0.4630486977182269

In [ ]:
coef_df = pd.DataFrame({'Feature': X.columns, 'Coefficient': model.coef_})
coef_df_sorted = coef_df.sort_values(by='Coefficient', ascending=False)

top_5 = coef_df_sorted.head(5)

# Plot

plt.barh(top_5['Feature'], top_5['Coefficient'])
plt.xlabel(xlabel = 'Predicted Contribution', size= 25)
plt.gca().invert_yaxis()  
plt.xticks(size= 25)
plt.yticks(size= 25)
plt.ylabel( size= 25)
plt.show()

plt.show()

**Random Forest**

**100 trees**

In [ ]:

# Create a RandomForestRegressor object
model2 = RandomForestRegressor(n_estimators=100, random_state=42)  # You can adjust the number of trees with n_estimators

# Fit the model to the training data
model2.fit(X_train, y_train)

# Make predictions on the test data
predictions = model2.predict(X_test)

In [ ]:
# Calculate evaluation metrics
mse_2 = mean_squared_error(y_test, predictions)
r2_2 = r2_score(y_test, predictions)
mae_2 = mean_absolute_error(y_test, predictions)
print("Mean Squared Error (MSE):", mse_2)
print("R-squared:", r2_2)
print("Mean Absolute Error (MAE):", mae_2)

In [ ]:
feature_importances = model2.feature_importances_
importance_df = pd.DataFrame({'Feature': X.columns, 'Importance': feature_importances})
importance_df_sorted = importance_df.sort_values(by='Importance', ascending=False)

# Plot

plt.barh(importance_df_sorted['Feature'][:5], importance_df_sorted['Importance'][:5])
plt.xlabel(xlabel = 'Predicted Contribution', size= 25)
plt.gca().invert_yaxis()  
plt.xticks(size= 25)
plt.yticks(size= 25)
plt.ylabel(size= 25)
plt.show()

plt.show()

In [ ]:
tree_to_plot = model2.estimators_[0]

# Plot the selected tree
plt.figure(figsize=(10,6))
plot_tree(tree_to_plot, filled=True, feature_names=X_train.columns, max_depth=2)
# Modify text properties in the plotted tree
for text in plt.gca().texts:
    text.set_fontsize(11)  # Adjust the fontsize as needed


plt.show()

**150 trees**

In [ ]:

# Create a RandomForestRegressor object
model3 = RandomForestRegressor(n_estimators=150, random_state=42)  # You can adjust the number of trees with n_estimators

# Fit the model to the training data
model3.fit(X_train, y_train)

# Make predictions on the test data
predictions = model3.predict(X_test)

In [ ]:
# Calculate evaluation metrics
mse_3 = mean_squared_error(y_test, predictions)
r2_3 = r2_score(y_test, predictions)
mae_3 = mean_absolute_error(y_test, predictions)
print("Mean Squared Error (MSE):", mse_3)
print("R-squared:", r2_3)
print("Mean Absolute Error (MAE):", mae_3)

In [ ]:
feature_importances = model3.feature_importances_
importance_df = pd.DataFrame({'Feature': X_train.columns, 'Importance': feature_importances})
importance_df_sorted = importance_df.sort_values(by='Importance', ascending=False)

# Plot

plt.barh(importance_df_sorted['Feature'][:5], importance_df_sorted['Importance'][:5])
plt.xlabel('Importance')
plt.title('Top 5 Feature Importances')
plt.gca().invert_yaxis()  
plt.show()

In [ ]:
tree_to_plot = model3.estimators_[0]

# Plot the selected tree
plt.figure(figsize=(10,6))
plot_tree(tree_to_plot, filled=True, feature_names=X_train.columns, max_depth=2)
# Modify text properties in the plotted tree
for text in plt.gca().texts:
    text.set_fontsize(11)  # Adjust the fontsize as needed


plt.show()

# SVR and LASSO

In [ ]:
from sklearn.svm import SVR

svr_model = SVR(kernel='rbf', C=100, gamma='scale', epsilon=0.1)
svr_model.fit(X_train, y_train)

y_test_pred = svr_model.predict(X_test)

# Evaluate 
mse = mean_squared_error(y_test, y_test_pred)
r2 = r2_score(y_test, y_test_pred)
mae = mean_absolute_error(y_test, y_test_pred)
print("Mean Squared Error:", mse)
print("R-squared Score:", r2)
print("Mean Absolute Error (MAE):", mae)

In [ ]:
from sklearn.linear_model import Lasso


lasso_model = Lasso()  
lasso_model.fit(X_train, y_train)

y_test_pred = lasso_model.predict(X_test)

# Evaluate 
mse = mean_squared_error(y_test, y_test_pred)
r2 = r2_score(y_test, y_test_pred)
mae = mean_absolute_error(y_test, y_test_pred)
print("Mean Squared Error:", mse)
print("R-squared Score:", r2)
print("Mean Absolute Error (MAE):", mae)

# Zero-inflated regressor

In [17]:
#pip install scikit-lego

Collecting scikit-lego
  Downloading scikit_lego-0.8.2-py2.py3-none-any.whl (211 kB)
                                              0.0/211.8 kB ? eta -:--:--
     ---                                   20.5/211.8 kB 640.0 kB/s eta 0:00:01
     ----------                            61.4/211.8 kB 656.4 kB/s eta 0:00:01
     -------------------------------------- 211.8/211.8 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.1.5 in c:\users\nguye\anaconda3\lib\site-packages (from scikit-lego) (1.5.3)
Requirement already satisfied: scikit-learn>=1.0 in c:\users\nguye\anaconda3\lib\site-packages (from scikit-lego) (1.2.2)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\nguye\anaconda3\lib\site-packages (from pandas>=1.1.5->scikit-lego) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\nguye\anaconda3\lib\site-packages (from pandas>=1.1.5->scikit-lego) (2022.7)
Requirement already satisfied: numpy>=1.20.3 in c:\users\nguye\anaconda3\lib\site-packages (from pandas>=1.1.5->scikit-lego) (1.24.3)
Requirement already satisfied: scipy>=1.3.2 in c:\users\nguye\anaconda3\lib\site-packages (from scikit-learn>=1.0->scikit-lego) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\nguye\anaconda3\lib\site-packages (from scikit-learn>=1.0->scikit-lego) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\nguye\anaconda3\lib\site-packages (from scikit-learn>=1.0->scikit-lego) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\users\nguye\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas>=1.1.5->scikit-lego) (1.16.0)
Installing collected packages: scikit-lego
Successfully installed scikit-lego-0.8.2
Note: you may need to restart the kernel to use updated packages.

In [19]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from sklego.meta import ZeroInflatedRegressor

# Instantiate the zero-inflated regressor.
zir = ZeroInflatedRegressor(
    classifier=SVC(),
    regressor=LinearRegression()
)

# Easy fit!
zir.fit(X_train, y_train)
pred = zir.predict(X_test)

In [21]:
#print('model intercept :', zir.intercept_) 
#print('model coefficients : ', zir.coef_) 
# Calculate Mean Squared Error (MSE)
mse = mean_squared_error(y_test, pred)
print("Mean Squared Error (MSE):", mse)

# Calculate R-squared
r2 = r2_score(y_test, pred)
print("R-squared:", r2)

# Calculate Mean Absolute Error (MAE)
mae = mean_absolute_error(y_test, pred)
print("Mean Absolute Error (MAE):", mae)

Mean Squared Error (MSE): 0.8360233593537983
R-squared: 0.9025884948664429
Mean Absolute Error (MAE): 0.4548307311846409

# Resampling

In [33]:
def bootstrap_dataframe(dataframe, num_samples):
    n = len(dataframe)
    bootstrap_samples = []
    for _ in range(num_samples):
        # Generate random indices with replacement
        indices = np.random.choice(n, size=n, replace=True)
        # Create a bootstrap sample DataFrame using the selected indices
        bootstrap_sample = dataframe.iloc[indices]
        bootstrap_samples.append(bootstrap_sample)
    return bootstrap_samples

In [37]:
boot_samples_df = bootstrap_dataframe(df_encoded, 100)

In [38]:
boot_samples_df = pd.concat(boot_samples_df, ignore_index=True)